### ISSUE TITLE
Error in month(today) : could not find function "month"

### ISSUE THREAD

**Issue by rois286** [johnros/Rcourse#15]
When trying to create a PDF for chapter 3, the following error occurs:
```
Quitting from lines 895-901 (25-r-basics.Rmd) 
Error in month(today) : could not find function "month"
Calls: <Anonymous> ... handle -> withCallingHandlers -> withVisible -> eval -> eval
Execution halted
```
Because the ```library(lubridate)``` command (and the entire elaboration section for that package) appears only on line 938 while the ```month(today)``` appears on line 900.

Adding this line before month, solves the problem but messes up the chronology.

**Comment by johnros** [comment]
You are right. 
I removed the month() example.
